language: node_js
node_js:
  - "node"
branches:
  only:
  - master
  - dev
install:
  - npm install bower
  - npm install polymer-cli
  - node_modules/.bin/bower install --allow-root
  - cd functions/ && npm install && cd ..
before_script:
  - if [ "$TRAVIS_TAG" ]; then sed -i '' 's/corpopong-dev/corpopong/' ./src/corpopong-app/corpopong-app.html; fi
  - if [ "$TRAVIS_TAG" ]; then sed -i '' 's/AIzaSyB1jdeJaOejjpVtL5SOQrkiARsmAdeyuOk/AIzaSyDbtyN2aekFdVcqWP-YbclBHkwknQOrk6U/' ./src/corpopong-app/corpopong-app.html; fi
  - if [ "$TRAVIS_TAG" ]; then sed -i '' 's/414017409980/182128657968/' ./src/corpopong-app/corpopong-app.html; fi
script:
  - node_modules/.bin/polymer build
deploy:
  - provider: firebase
    project: "corpopong-dev"
    skip_cleanup: true
    on:
      condition: "-z $TRAVIS_TAG"
      all_branches: true
  - provider: firebase
    project: "corpopong"
    skip_cleanup: true
    on:
      tags: true
      all_branches: true
